version: "3.8"
services:
  auth:
    build:
      context: .
      dockerfile: docker/auth/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DEMO_AUTH_PORT=8001

  collector:
    build:
      context: .
      dockerfile: docker/collector/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - collector_data:/app/data

  backend:
    build:
      context: .
      dockerfile: docker/dashboard-backend/Dockerfile
    ports:
      - "8010:8010"
    environment:
      - DASHBOARD_BACKEND_PORT=8010
      - AUTH_BASE_URL=http://auth:8001
      - COLLECTOR_BASE_URL=http://collector:8000

  frontend:
    build:
      context: .
      dockerfile: docker/dashboard-frontend/Dockerfile
    ports:
      - "5173:3000"
    environment:
      # Runtime environment variables (read by /api/config endpoint)
      # These work the same way as backend services
      - DASHBOARD_BACKEND_URL=http://localhost:8010
      - AUTH_SERVICE_URL=http://localhost:8001
      - COLLECTOR_URL=http://localhost:8000

volumes:
  collector_data:
