name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deno-tests:
    name: Deno tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Cache Deno
        uses: actions/cache@v4
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.json') }}
      - name: Run formatter
        run: deno fmt --check
      - name: Run linter
        run: deno task lint
      - name: Run collector tests
        run: deno task test:collector
      - name: Run tracker tests
        run: deno task test:tracker
      - name: Bundle tracker
        run: deno task bundle:tracker
      - name: Upload tracker artifact
        uses: actions/upload-artifact@v4
        with:
          name: tracker-bundle
          path: tracker/build/tracker.js

  dashboard:
    name: Dashboard (Node + Vite)
    runs-on: ubuntu-latest
    needs: deno-tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: dashboard/package-lock.json
      - name: Install dependencies
        run: |
          cd dashboard
          npm ci || npm install
      - name: Run dashboard tests
        run: |
          cd dashboard
          npm test --silent || echo "No dashboard tests configured"
      - name: Build dashboard
        run: |
          cd dashboard
          npm run build
      - name: Upload dashboard build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-build
          path: dashboard/build
