name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  deno-tests:
    name: Deno tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1
      - name: Cache Deno
        uses: actions/cache@v4
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.json') }}
      - name: Run formatter
        run: deno task fmt
      - name: Run linter
        run: deno task lint
      - name: Run collector tests
        run: deno task test:collector
      - name: Run tracker tests
        run: deno task test:tracker
      - name: Bundle tracker
        run: deno task bundle:tracker
      - name: Upload tracker artifact
        uses: actions/upload-artifact@v4
        with:
          name: tracker-bundle
          path: tracker-src/build/tracker.js

  dashboard:
    name: Dashboard (Node + Vite)
    runs-on: ubuntu-latest
    needs: deno-tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          cd dashboard
          npm ci
      - name: Run dashboard tests
        run: |
          cd dashboard
          npm test --silent
      - name: Build dashboard
        run: |
          cd dashboard
          npm run build
      - name: Upload dashboard build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-build
          path: dashboard/build
